#! /bin/bash
list_ec2_replicas=("ec2-52-0-73-113.compute-1.amazonaws.com"
"ec2-52-16-219-28.eu-west-1.compute.amazonaws.com"
"ec2-52-11-8-29.us-west-2.compute.amazonaws.com"      
"ec2-52-8-12-101.us-west-1.compute.amazonaws.com"       
"ec2-52-28-48-84.eu-central-1.compute.amazonaws.com"
"ec2-52-68-12-77.ap-northeast-1.compute.amazonaws.com"
"ec2-52-74-143-5.ap-southeast-1.compute.amazonaws.com"
"ec2-52-64-63-125.ap-southeast-2.compute.amazonaws.com"
"ec2-54-94-214-108.sa-east-1.compute.amazonaws.com")

while getopts "p:o:u:n:i:" arg
do
    case $arg in
        p) 
            ;;
        o) 
            ;;
        u) 
            username=$OPTARG
            
            ;;
        n) 
            ;;
        i) 
            key_file=$OPTARG
            
            ;;
        ?)
            echo "Incorrect arguments!!"
        exit 1
        ;;
        esac
done

for a_replica in "${list_ec2_replicas[@]}"
do
    ssh -i $key_file $username@$a_replica 'killall python > /dev/null 2>&1 &'
done

dns_hosted_on_server_name=cs5700cdnproject.ccs.neu.edu
ssh -i $key_file $username@$dns_hosted_on_server_name 'killall python > /dev/null 2>&1 &'